[versions]
slf4jVersion = "2.0.13"
logbackVersion = "1.5.6"
lombokVersion = "1.18.32"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jVersion" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" }
